package com.blueradix.android.monstersrecyclerviewwithsqlite;

import android.content.Intent;
import android.os.Bundle;

import com.blueradix.android.monstersrecyclerviewwithsqlite.activities.AddMonsterScrollingActivity;
import com.blueradix.android.monstersrecyclerviewwithsqlite.entities.Monster;
import com.blueradix.android.monstersrecyclerviewwithsqlite.entities.Task;
import com.blueradix.android.monstersrecyclerviewwithsqlite.recyclerview.TaskRecyclerViewAdapter;
import com.blueradix.android.monstersrecyclerviewwithsqlite.service.DataService;
import com.google.android.material.floatingactionbutton.FloatingActionButton;
import com.google.android.material.snackbar.Snackbar;

import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.view.View;
import android.view.Menu;
import android.view.MenuItem;

import java.util.ArrayList;
import java.util.List;

import static com.blueradix.android.monstersrecyclerviewwithsqlite.entities.Constants.ADD_MONSTER_ACTIVITY_CODE;
import static com.blueradix.android.monstersrecyclerviewwithsqlite.entities.Constants.ADD_TASK_ACTIVITY_CODE;

public class MainActivity extends AppCompatActivity {

    private DataService monsterDataService;
    private Monster monster;

    private DataService taskDataService;
    private View rootView;
    private List<Task> tasks;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        FloatingActionButton fab = findViewById(R.id.fab);
        fab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                addNewMonster();
            }
        });
        rootView = findViewById(android.R.id.content).getRootView();


        RecyclerView taskRecyclerView = findViewById(R.id.taskRecyclerView);

        LinearLayoutManager linearLayoutManager = new LinearLayoutManager(this);
        //LinearLayoutManager.setOrientation(Line)
        linearLayoutManager.setOrientation(LinearLayoutManager.VERTICAL);


        //GridsLayoutManager gridLayoutManager = new GridLayoutManager(this, 2, GridsLayoutManager,VERTICAL, false);
        taskRecyclerView.setLayoutManager(linearLayoutManager);




        //Load Data from the database
        monsterDataService = new DataService();
        monsterDataService.init(this);
        /**
         * TODO: call the database, to get allMonsters
         */
        tasks = taskDataService.getTasks();    // fix 1



        /**
         * TODO: create a RecyclerViewAdapter and pass the data
         */

        //TaskRecyclerViewAdapter adapter
        TaskRecyclerViewAdapter adapter = new TaskRecyclerViewAdapter(tasks, this);


        /**
         * TODO: set the adapter to the RecyclerView
         */
        taskRecyclerView.setAdapter(adapter);

    }

    private void addNewMonster() {
        Intent goToAddCreateMonster = new Intent(this, AddMonsterScrollingActivity.class);
        startActivityForResult(goToAddCreateMonster, ADD_MONSTER_ACTIVITY_CODE);
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if(requestCode == ADD_TASK_ACTIVITY_CODE){
            if(resultCode == RESULT_OK){
               // addMonster(data);
                addTask(data);
            }
        }

    }

    private void addTask(Intent data) {
        String message;
        //Monster monster = (Monster) data.getSerializableExtra(Monster.MONSTER_KEY);
        Task task = (Task) data.getSerializableExtra(Task.TASK_KEY);
        //public static final String TASK_KEY = "task_key";

        //insert your monster into the DB
        //Long result = monsterDataService.(monster);
        Long result = taskDataService.(data);
        //result holds the autogenerated id in the table
        if(result > 0){
            message = "Your task was created with id: "+ result;
        }else{
            message = "We couldn't create your task, try again";
        }
        Snackbar.make(rootView, message, Snackbar.LENGTH_SHORT).show();
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }
}
